Extend fix for on-disk version detection on Bookworm (Closes: #1033791)
Commit 4ab7834e added a fix for Debian bug #1029720 [1] but only on the
code path for compressed kernel images. However, it seems like the same
issue also exists on non-compressed images that are used at least on
some ARM64 machines as reported in Debian bug #1033791 [2].

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1029720
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033791

diff --git a/debian/patches/dsa/check_running_kernel_bookworm_fix b/debian/patches/dsa/check_running_kernel_bookworm_fix
--- a/debian/patches/dsa/check_running_kernel_bookworm_fix
+++ b/debian/patches/dsa/check_running_kernel_bookworm_fix
@@ -9,3 +9,12 @@
  			if [ -x /usr/bin/lsb_release ] ; then
  				vendor=$(lsb_release -i -s)
  				if [ -n "$vendor" ] && [ "xDebian" != "x$vendor" ] ; then
+@@ -211,7 +211,7 @@
+ 				fi
+ 			fi
+ 			[ -z "$on_disk_version" ] || continue
+-			on_disk_version="`cat "$on_disk" | $STRINGS | grep 'Linux version' | head -n1`"
++			on_disk_version="`cat "$on_disk" | $STRINGS | grep 'Linux version' | tail -n1`"
+ 			[ -z "$on_disk_version" ] || continue
+ 
+ 			echo "UNKNOWN: Failed to get a version string from image $on_disk"
