d/p/dsa/check_running_kernel_jessie_centos_fix: Adding some more binary suggestions

diff --git a/debian/patches/dsa/check_running_kernel_jessie_centos_fix b/debian/patches/dsa/check_running_kernel_jessie_centos_fix
--- a/debian/patches/dsa/check_running_kernel_jessie_centos_fix
+++ b/debian/patches/dsa/check_running_kernel_jessie_centos_fix
@@ -1,18 +1,18 @@
 --- a/dsa/checks/dsa-check-running-kernel
 +++ b/dsa/checks/dsa-check-running-kernel
-@@ -131,6 +131,11 @@
+@@ -132,6 +132,11 @@
  	filter="$3"
  	hdroff="$4"
  
 +	if ! which $filter >/dev/null; then
-+		echo "UNKNOWN: filter command '$filter' missing, perhaps install xz-utils?" >&2
++		echo "UNKNOWN: filter command '$filter' missing, perhaps install xz-utils, lz4 or lzop?" >&2
 +		exit $UNKNOWN
 +	fi
 +
  	get_offset "$image" $header | head -n 5 | while read off; do
  		(if [ "$off" != 0 ]; then
  		   dd ibs="$((off+hdroff))" skip=1 count=0
-@@ -182,9 +187,8 @@
+@@ -183,9 +188,8 @@
  
  searched=""
  for on_disk in \
@@ -24,7 +24,7 @@
  
  	if [ -e "$on_disk" ]; then
  		if [ -z "$STRINGS" ]; then
-@@ -196,12 +200,12 @@
+@@ -197,12 +201,12 @@
  			if [ -x /usr/bin/lsb_release ] ; then
  				vendor=$(lsb_release -i -s)
  				if [ -n "$vendor" ] && [ "xDebian" != "x$vendor" ] ; then
